=== wangyupub/XbeeProject/meta/command_script.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by Yu Wang (Truthful Giant) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CommandTestScript">
		<xs:annotation>
			<xs:documentation>Test Script Format to Automate Testing of Commands</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Commands">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Command" type="AbstractCommand" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="CommandDelayInterval" type="xs:unsignedInt" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AbstractCommand" abstract="true"/>
	<xs:complexType name="SetSingleSwitchCommand">
		<xs:complexContent>
			<xs:extension base="AbstractCommand">
				<xs:sequence>
					<xs:element name="SwitchIndex" type="xs:unsignedShort"/>
					<xs:element name="SwitchStatus" type="xs:unsignedByte"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="GetSingleSwitchCommand">
		<xs:complexContent>
			<xs:extension base="AbstractCommand">
				<xs:sequence>
					<xs:element name="SwitchIndex" type="xs:unsignedShort"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SetMultipleSwitchesCommand">
		<xs:complexContent>
			<xs:extension base="AbstractCommand">
				<xs:sequence>
					<xs:element name="SwitchOffset" type="xs:unsignedShort"/>
					<xs:element name="SwitchBitMask" type="xs:unsignedLong"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="GetMultipleSwitchesCommand">
		<xs:complexContent>
			<xs:extension base="AbstractCommand">
				<xs:sequence>
					<xs:element name="SwitchOffset" type="xs:unsignedShort"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="GetNumSwitchesCommand">
		<xs:complexContent>
			<xs:extension base="AbstractCommand"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SetSingleSwitchDelayCommand">
		<xs:complexContent>
			<xs:extension base="AbstractCommand">
				<xs:sequence>
					<xs:element name="SwitchIndex" type="xs:unsignedShort"/>
					<xs:element name="SwitchStatus" type="xs:unsignedByte"/>
					<xs:element name="Delay" type="xs:unsignedShort"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PassThroughCommand">
		<xs:complexContent>
			<xs:extension base="AbstractCommand">
				<xs:sequence>
					<xs:element name="Data" type="xs:base64Binary"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CompositeCommand">
		<xs:complexContent>
			<xs:extension base="AbstractCommand">
				<xs:sequence>
					<xs:element name="Commands">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Command" type="AbstractCommand" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== wangyupub/XbeeProject/meta/scripts/setsingleswitch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by Yu Wang (NA) -->
<CommandTestScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="command_script.xsd" CommandDelayInterval="1">
	<Commands>
		<Command xsi:type="PassThroughCommand">
			<Data>ZA==</Data>
		</Command>
		<Command xsi:type="GetSingleSwitchCommand">
			<SwitchIndex>1</SwitchIndex>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>bg==</Data>
		</Command>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>1</SwitchIndex>
			<SwitchStatus>1</SwitchStatus>
		</Command>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>1</SwitchIndex>
			<SwitchStatus>0</SwitchStatus>
		</Command>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>3</SwitchIndex>
			<SwitchStatus>1</SwitchStatus>
		</Command>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>3</SwitchIndex>
			<SwitchStatus>0</SwitchStatus>
		</Command>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>2</SwitchIndex>
			<SwitchStatus>1</SwitchStatus>
		</Command>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>2</SwitchIndex>
			<SwitchStatus>0</SwitchStatus>
		</Command>
	</Commands>
</CommandTestScript>

=== wangyupub/XbeeProject/meta/scripts/commandpack.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by Yu Wang (NA) -->
<CommandTestScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="command_script.xsd" CommandDelayInterval="0">
	<Commands>
<Command xsi:type="CompositeCommand">
<Commands>
		<Command xsi:type="PassThroughCommand">
			<Data>ZA==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>bg==</Data>
		</Command>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>0</SwitchIndex>
			<SwitchStatus>1</SwitchStatus>
		</Command>
		<Command xsi:type="SetSingleSwitchDelayCommand">
			<SwitchIndex>1</SwitchIndex>
			<SwitchStatus>1</SwitchStatus>
			<Delay>2</Delay>
		</Command>
		<Command xsi:type="SetSingleSwitchDelayCommand">
			<SwitchIndex>2</SwitchIndex>
			<SwitchStatus>1</SwitchStatus>
			<Delay>4</Delay>
		</Command>
		<Command xsi:type="SetSingleSwitchDelayCommand">
			<SwitchIndex>3</SwitchIndex>
			<SwitchStatus>1</SwitchStatus>
			<Delay>6</Delay>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>ZA==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>bg==</Data>
		</Command>
		</Commands>
		</Command>
  </Commands>
</CommandTestScript>

=== wangyupub/XbeeProject/meta/scripts/passthrough.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by Yu Wang (NA) -->
<CommandTestScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="command_script.xsd" CommandDelayInterval="1">
	<Commands>
		<Command xsi:type="PassThroughCommand">
			<Data>ZQ==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>Zg==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>Zw==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>aA==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>bw==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>cA==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>cQ==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>cg==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>ZA==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>bg==</Data>
		</Command>
	</Commands>
</CommandTestScript>

=== wangyupub/XbeeProject/meta/scripts/setmultipleswitches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by Yu Wang (NA) -->
<CommandTestScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="command_script.xsd" CommandDelayInterval="0">
	<Commands>
<Command xsi:type="CompositeCommand">
<Commands>
		<Command xsi:type="PassThroughCommand">
			<Data>ZA==</Data>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>bg==</Data>
		</Command>
		<Command xsi:type="SetMultipleSwitchesCommand">
			<SwitchOffset>0</SwitchOffset>
			<SwitchBitMask>12297078782535139328</SwitchBitMask>
		</Command>
		</Commands>
		</Command>
  </Commands>
</CommandTestScript>

=== wangyupub/XbeeProject/meta/scripts/script.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by Yu Wang (NA) -->
<CommandTestScript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="command_script.xsd" CommandDelayInterval="4">
	<Commands>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>2</SwitchIndex>
			<SwitchStatus>1</SwitchStatus>
		</Command>
		<Command xsi:type="SetSingleSwitchCommand">
			<SwitchIndex>2</SwitchIndex>
			<SwitchStatus>0</SwitchStatus>
		</Command>
		<Command xsi:type="PassThroughCommand">
			<Data>0x39</Data>
		</Command>
	</Commands>
</CommandTestScript>
